'use client';

import { suggestYoutubeIdeas, type SuggestYoutubeIdeasOutput } from '@/ai/flows/suggest-youtube-ideas';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Loader2, Lightbulb } from 'lucide-react';
import React, { useState, useEffect } from 'react';

export default function ContentIdeas() {
    const [ideas, setIdeas] = useState<SuggestYoutubeIdeasOutput['ideas']>([]);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        async function fetchIdeas() {
            setIsLoading(true);
            try {
                const result = await suggestYoutubeIdeas({
                    channelTopic: "AI and Social Media Technology",
                    targetAudience: "Marketing professionals, content creators, and small business owners"
                });
                setIdeas(result.ideas);
            } catch (error) {
                console.error("Failed to fetch YouTube ideas:", error);
            } finally {
                setIsLoading(false);
            }
        }
        fetchIdeas();
    }, []);

    return (
        <Card>
            <CardHeader>
                <CardTitle>AI-Powered Content Ideas</CardTitle>
                <CardDescription>Fresh video ideas generated by AI to keep your channel growing.</CardDescription>
            </CardHeader>
            <CardContent>
                {isLoading ? (
                    <div className="flex justify-center items-center h-40">
                        <Loader2 className="animate-spin text-primary" />
                    </div>
                ) : (
                    <ul className="space-y-4">
                        {ideas.map((idea, index) => (
                            <li key={index} className="p-3 rounded-lg border bg-card/50">
                                <h4 className="font-semibold flex items-center gap-2">
                                    <Lightbulb className="size-4 text-yellow-400"/> {idea.title}
                                </h4>
                                <p className="text-sm text-muted-foreground mt-1">{idea.description}</p>
                                <p className="text-xs text-muted-foreground/80 mt-2"><b>Thumbnail Idea:</b> {idea.thumbnailConcept}</p>
                            </li>
                        ))}
                    </ul>
                )}
            </CardContent>
        </Card>
    );
}
